-- AlterTable
ALTER TABLE "User" ADD COLUMN     "allowedmaxgb" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "currentConfigs" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "currentgb" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "maxConfigs" INTEGER NOT NULL DEFAULT 5;
